Repository TEAM-KN/daily_dev_front, pull requests merged in 2023-08, with the labels that each got.

#50 fix: 로그인, 회원가입 token 정보 LocalStorage 저장
  src/hook/useSetUserInfo.tsx
  src/service/apis.ts
Labels: 🍀프론트

#51 #42 회원탈퇴 기능 추가
  src/hook/useLogin.tsx
  src/hook/useLogout.tsx
  src/hook/useSetUserInfo.tsx
  src/service/apis.ts
  src/view/MyPage.tsx
Labels: 🍀프론트

#52 Develop
  src/hook/useLogin.tsx
  src/hook/useLogout.tsx
  src/hook/useSetUserInfo.tsx
  src/service/apis.ts
  src/view/MyPage.tsx
Labels: 🍀프론트, 👨🏻‍💻개발

#55 #54 AuthRoutes 접근시 로그인 페이지로 리디렉션 처리, 파일 정리
  src/App.tsx
  src/components/MoreButton.tsx
  src/components/Pagination.tsx
  src/components/PostList.tsx
  src/components/SitesButton.tsx
  src/hooks/useLogin.tsx
  src/hooks/useLogout.tsx
  src/hooks/useSetUserInfo.tsx
  src/layouts/EditService.tsx
  src/layouts/SavedService.tsx
  src/router/Auth.tsx
  src/router/Main.tsx
  src/router/index.tsx
  src/types/commonTypes.ts
  src/view/Login.tsx
  src/view/MyPage.tsx
  src/view/Register.tsx
  src/view/RegisterComplete.tsx
  src/view/authentication/login/index.ts
  tsconfig.json
Labels: 🍀프론트

#56 #53 Main 페이지 레이이웃 분리, 공통 컴포넌트 수정
  src/components/Loading.tsx
  src/components/PostItem.tsx
  src/components/SitesButton.tsx
  src/components/buttons/MoreButton.tsx
  src/components/buttons/ScrollTopButton.tsx
  src/components/buttons/TabButton.tsx
  src/components/labels/SiteLabel.tsx
  src/components/pagination.jsx/Pagination.tsx
  src/layouts/EditService.tsx
  src/layouts/Header.tsx
  src/layouts/PostList.tsx
  src/layouts/SavedService.tsx
  src/layouts/SiteTabList.tsx
  src/types/commonTypes.ts
  src/view/Landing.tsx
  src/view/Login.tsx
  src/view/Main.tsx
  src/view/MyPage.tsx
  src/view/Register.tsx
  src/view/RegisterComplete.tsx
Labels: 🍀프론트

#57 Develop
  src/App.tsx
  src/components/Loading.tsx
  src/components/PostItem.tsx
  src/components/SitesButton.tsx
  src/components/buttons/MoreButton.tsx
  src/components/buttons/ScrollTopButton.tsx
  src/components/buttons/TabButton.tsx
  src/components/labels/SiteLabel.tsx
  src/components/pagination.jsx/Pagination.tsx
  src/hooks/useLogin.tsx
  src/hooks/useLogout.tsx
  src/hooks/useSetUserInfo.tsx
  src/layouts/EditService.tsx
  src/layouts/Header.tsx
  src/layouts/PostList.tsx
  src/layouts/SavedService.tsx
  src/layouts/SiteTabList.tsx
  src/router/Auth.tsx
  src/router/Main.tsx
  src/router/index.tsx
  src/types/commonTypes.ts
  src/view/Landing.tsx
  src/view/Login.tsx
  src/view/Main.tsx
  src/view/MyPage.tsx
  src/view/Register.tsx
  src/view/RegisterComplete.tsx
  src/view/authentication/login/index.ts
  tsconfig.json
Labels: 🤦🏻‍♂️버그, 🍀프론트, 👨🏻‍💻개발

#58 Feature/43
  src/components/labels/SiteLabel.tsx
  src/hooks/useLogin.tsx
  src/hooks/useSetUserInfo.tsx
  src/layouts/EditService.tsx
  src/layouts/SavedService.tsx
  src/recoil/userInfo.tsx
  src/service/apis.ts
  src/types/commonTypes.ts
  src/view/MyPage.tsx
  src/view/Register.tsx
  src/view/RegisterComplete.tsx
Labels: 🍀프론트

#59 #46 랜딩, 마이페이지 css 수정
  src/view/Landing.tsx
  src/view/MyPage.tsx
Labels: 🍀프론트

#64 fix: landing 페이지 텍스트 내용 수정
  src/view/Landing.tsx
Labels: 🍀프론트

#66 #65 회원 정보 수정 기능 추가
  src/App.tsx
  src/components/Modal/Alert.tsx
  src/components/Modal/Confirm.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/PWConfirm.tsx
  src/hooks/useSetUserInfo.tsx
  src/layouts/EditService.tsx
  src/layouts/EditUserInfoList.tsx/EditButtons.tsx
  src/layouts/EditUserInfoList.tsx/Email.tsx
  src/layouts/EditUserInfoList.tsx/Nickname.tsx
  src/layouts/EditUserInfoList.tsx/Password.tsx
  src/layouts/EditUserInfoList.tsx/Service.tsx
  src/layouts/SavedService.tsx
  src/recoil/useModalState.tsx
  src/recoil/userInfoState.tsx
  src/router/Auth.tsx
  src/service/apis.ts
  src/view/EditUserInfo.tsx
  src/view/Landing.tsx
  src/view/Main.tsx
  src/view/MyPage.tsx
  src/view/Register.tsx
  src/view/RegisterComplete.tsx
Labels: 🍀프론트

#67 회원정보수정 기능 추가, modal 컴포넌트 추가
  src/App.tsx
  src/components/Modal/Alert.tsx
  src/components/Modal/Confirm.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/PWConfirm.tsx
  src/hooks/useSetUserInfo.tsx
  src/layouts/EditService.tsx
  src/layouts/EditUserInfoList.tsx/EditButtons.tsx
  src/layouts/EditUserInfoList.tsx/Email.tsx
  src/layouts/EditUserInfoList.tsx/Nickname.tsx
  src/layouts/EditUserInfoList.tsx/Password.tsx
  src/layouts/EditUserInfoList.tsx/Service.tsx
  src/layouts/SavedService.tsx
  src/recoil/useModalState.tsx
  src/recoil/userInfoState.tsx
  src/router/Auth.tsx
  src/service/apis.ts
  src/view/EditUserInfo.tsx
  src/view/Landing.tsx
  src/view/Main.tsx
  src/view/MyPage.tsx
  src/view/Register.tsx
  src/view/RegisterComplete.tsx
Labels: 🍀프론트

#71 #70 fix: 메인 컨텐츠 리스트 최신순으로 정렬
  src/layouts/PostList.tsx
Labels: 🍀프론트

#73 #72 feat: 라인, 지마켓 라벨 추가, 간격 수정
  src/components/labels/SiteLabel.tsx
  src/layouts/EditUserInfoList.tsx/Service.tsx
  src/layouts/SavedService.tsx
  src/view/MyPage.tsx
Labels: 🍀프론트

#74 #68 fix: input 스타일 수정, 반응형 텍스트 크기 수정
  src/components/PostItem.tsx
  src/components/buttons/MoreButton.tsx
  src/components/buttons/TabButton.tsx
  src/layouts/EditUserInfoList.tsx/Email.tsx
  src/layouts/EditUserInfoList.tsx/Nickname.tsx
  src/layouts/EditUserInfoList.tsx/Password.tsx
  src/layouts/EditUserInfoList.tsx/Service.tsx
  src/styles/style.input.tsx
  src/view/EditUserInfo.tsx
  src/view/Login.tsx
  src/view/MyPage.tsx
  src/view/Register.tsx
Labels: 🤦🏻‍♂️버그, 🍀프론트

#75 컨텐츠 리스트 최신순 정렬, 인풋 크로스브라우징 이슈 해결
  src/components/PostItem.tsx
  src/components/buttons/MoreButton.tsx
  src/components/buttons/TabButton.tsx
  src/components/labels/SiteLabel.tsx
  src/layouts/EditUserInfoList.tsx/Email.tsx
  src/layouts/EditUserInfoList.tsx/Nickname.tsx
  src/layouts/EditUserInfoList.tsx/Password.tsx
  src/layouts/EditUserInfoList.tsx/Service.tsx
  src/layouts/PostList.tsx
  src/layouts/SavedService.tsx
  src/styles/style.input.tsx
  src/view/EditUserInfo.tsx
  src/view/Login.tsx
  src/view/MyPage.tsx
  src/view/Register.tsx
Labels: 🤦🏻‍♂️버그, 🍀프론트

#77 #76 회원탈퇴 모달 적용, 지마켓 라벨코드 수정
  src/components/Modal/Alert.tsx
  src/components/labels/SiteLabel.tsx
  src/view/MyPage.tsx
Labels: 🍀프론트

#78 #76 회원탈퇴 모달 적용, 지마켓 라벨코드 수정
  src/components/Modal/Alert.tsx
  src/components/labels/SiteLabel.tsx
  src/view/MyPage.tsx
Labels: 🍀프론트
